### ISSUE TITLE
Connection error?

### ISSUE THREAD

**Issue by CMulas** [sschivo/ANIMO3#1]
Hello,

I'm trying to run ANIMO on Cytoscape but I'm getting this error every time... Any suggestion how to go around it? (I'm a biologist...)

This is what I get when I run Cytoscape/ANIMO from shell. 

```
animo.core.analyser.AnalysisException: Error during analysis: <pre>java.lang.Exception: [/Users/Carla/CytoscapeConfiguration/3/karaf_data/tmp/ANIMO7219678590825060215.xml] Verify result: 134
 empty result
HTTP/1.1 400 Bad Request
Date: Wed, 04 Mar 2020 16:48:28 GMT
Server: Apache/2.4
Content-Length: 226
Connection: close
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
</p>
</body></html>

 (current directory: /Applications/Cytoscape_v3.7.2/framework/.)

    at animo.core.analyser.uppaal.UppaalModelAnalyserSMC.analyze(UppaalModelAnalyserSMC.java:666)
    at animo.cytoscape.RunAction$RunTask.performNormalAnalysis(RunAction.java:141)
    at animo.cytoscape.RunAction$RunTask.run(RunAction.java:312)
    at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.innerRun(JDialogTaskManager.java:321)
    at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(JDialogTaskManager.java:352)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
</pre>
    at animo.core.analyser.uppaal.UppaalModelAnalyserSMC.analyze(UppaalModelAnalyserSMC.java:683)
    at animo.cytoscape.RunAction$RunTask.performNormalAnalysis(RunAction.java:141)
    at animo.cytoscape.RunAction$RunTask.run(RunAction.java:312)
    at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.innerRun(JDialogTaskManager.java:321)
    at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(JDialogTaskManager.java:352)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: [/Users/Carla/CytoscapeConfiguration/3/karaf_data/tmp/ANIMO7219678590825060215.xml] Verify result: 134
 empty result
HTTP/1.1 400 Bad Request
Date: Wed, 04 Mar 2020 16:48:28 GMT
Server: Apache/2.4
Content-Length: 226
Connection: close
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
</p>
</body></html>

 (current directory: /Applications/Cytoscape_v3.7.2/framework/.)

    at animo.core.analyser.uppaal.UppaalModelAnalyserSMC.analyze(UppaalModelAnalyserSMC.java:666)
    ... 9 more

```

Both Animo and Cytoscape are up to date with the latest version. I also tried installing Cytoscape 3.4 but I get exactly the same error... Not sure how to go forward so any suggest would be really appreciated!

**Comment by sschivo** [comment]
Hi,
I am a bit surprised by this error. The only thing I can think of is that UPPAAL is trying to connect to its own servers to do some "license verification" or similar. Did you try to open the UPPAAL program itself while connected to the internet? If you can open UPPAAL and it doesn't give any error, try again with the ANIMO analysis.
Also, I see that you are using MacOS. The latest version of MacOS (Catalina) has big problems with the latest version of UPPAAL (4.1.24). If you have those two versions together, it may be worth trying to use UPPAAL 4.1.19 instead, which seems to work fine. If you want to use another version of UPPAAL with ANIMO, after installing it you will need to change the location of the "verifyta" executable in ANIMO's options (the button down below in the ANIMO panel in Cyoscape).

I am curious about this problem, so please let me know if you manage to solve it or it still persists

Stefano

**Comment by CMulas** [comment]
Hi Stefano,

Thank you very much for the suggestion. Using UPPAAL 4.1.19 solved it!

Best wishes,

Carla
